apiVersion: apps/v1
kind: Deployment
metadata:
  name: akssimpleapplication-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akssimpleapplication
  template:
    metadata:
      labels:
        app: akssimpleapplication
    spec:
      containers:
      - name: AksApplication-master
        image: simpleacr.azurecr.io/reddivaripriyanka/aksapplication:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: priyankaaks
---
apiVersion: v1
kind: Service
metadata:
  name: akssimpleapplication
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: akssimpleapplication
